### ISSUE TITLE
One drive 链接失效了

### ISSUE THREAD

**Issue by cimszw** [yl305237731/yolov3_watermark#2]
另外是否可以把水印集合也在百度网盘分享? 
谢谢！

**Comment by cimszw** [comment]
带有水印的正样本又多少个？正负样本比例是多少？
水印图的生成是水印+正常图片生成的，还是网上直接找的？
如果是生成的，使用了多少水印和正常图片？可否把叠加生成水印图片的代码也上传？
谢谢！

**Comment by Bobo-y** [comment]
训练图片是水印+正常图片合成的，亮度、尺度在一定范围内随机变化打在图片任意位置上，使用PIL.Image.composite 。当然有能力加一些真实的更好，不然可能在生成的水印上能检测，真实的检测不出来。训练数据好几万张，非个人数据无法公开。我是一张图片上只打了一个水印，看你自己吧 @cimszw

**Comment by cimszw** [comment]
@yl305237731 谢谢你的答复。
1. 用到的水印大概有多少种？
2.另外下面的链接失效了，可否刷新一下链接？
Download pretrained weights for backend at:
https://1drv.ms/u/s!ApLdDEW3ut5fgQXa7GzSlG-mdza6
3. 我找到一个公开的数据集，80种水印，标注是用txt而非xml格式的，如(11 0.341359773371 0.609 0.416430594901 0.262),第一个是类别，也是VOC格式。请问包里有工具函数可以直接读么？
https://cloud.tencent.com/developer/article/1536395

**Comment by cimszw** [comment]
另外训练图片，是都只包括有水印的图片？
没有水印的正常图片是否包括？

**Comment by Bobo-y** [comment]
backend.h5   链接: https://pan.baidu.com/s/1OXoMWlL3MS7i1tc1AYssiw  密码: nutd  @cimszw 

训练图片只需要带水印图片就行了啊，目标检测没人用没目标的图片训吧，对于one-stage目标检测而言，负样本本来就极大于正样本了

它这个应该是归一化了, 没有处理这个格式的代码，你可以把txt恢复成xml就行
