### ISSUE TITLE
Error in training stage

### ISSUE THREAD

**Issue by cimszw** [yl305237731/yolov3_watermark#3]
File "D:\pycharm_projects\yolov3_watermark\generator.py", line 119, in __getitem__
    yolo[instance_count, grid_y, grid_x, max_index%3]      = 0
IndexError: index 52 is out of bounds for axis 1 with size 52

Use saved_weights_name or backend.h5 in train.py, I have this error message.
How can I fix this?

**Comment by Bobo-y** [comment]
This should be a problem of a bounding box coords. The coords  are beyond the image height or width.   I  suggest you print the current image height and width, image name, and center_x (center_x = .5 * (obj ['xmin'] + obj ['xmax']), line 101) and center_y (center_y = .5 * (obj ['ymin'] + obj ['ymax']), line 103)  in **getitem** , until an error is reported @cimszw , fix this image annotation

**Comment by cimszw** [comment]
Thank you. I'll try this.
One more question:  what is the version for python, keras and tensorflow.

**Comment by Bobo-y** [comment]
Package                Version   
---------------------- ----------
tensorflow             1.14.0   
Keras                  2.2.4     
Keras-Applications     1.0.8     
Keras-Preprocessing    1.1.0 
python     3.6.2
@cimszw
